name: Digger Workflow

on:
  workflow_dispatch:
  pull_request:
      branches: [ "main" ]

jobs:
  digger-job:
    runs-on: ubuntu-latest
    concurrency: deploy-group
    permissions:
      contents: write
      actions: write
      id-token: write
      pull-requests: write
      statuses: write

    steps:
      - uses: actions/checkout@v4

      - name: Run Digger
        uses: diggerhq/digger@vLatest
        with:
          setup-aws: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
