name: Digger Workflow

on:
  workflow_dispatch:

jobs:
  digger-job:
    runs-on: ubuntu-latest
    concurrency: deploy-group
    permissions:
      contents: write
      actions: write
      id-token: write
      pull-requests: write
      statuses: write

    steps:
      - name: digger run ${{github.event.inputs.id}}
        run: echo digger run ${{ inputs.id }}
      - uses: actions/checkout@v4
      - uses: diggerhq/digger@v0.4.17
        with:
          # digger-spec: ${{inputs.spec}}
          setup-aws: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          disable-locking: true
          digger-hostname: "https://cloud.digger.dev"
          digger-organisation: "digger"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
